pincode_db = {
    "110001": {
        "pincode": "110001",
        "city": "New_Delhi",
        "state": "Delhi",
        "district": "Central Delhi",
    },
    "400001": {
        "pincode": "400001",
        "city": "Mumbai",
        "state": "Maharashtra",
        "district": "Mumbai",
    },
    "560001": {
        "pincode": "560001",
        "city": "Bengaluru",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
    },
    "600001": {
        "pincode": "600001",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "district": "Chennai",
    },
    "700001": {
        "pincode": "700001",
        "city": "Kolkata",
        "state": "West Bengal",
        "district": "Kolkata",
    },
    "500001": {
        "pincode": "500001",
        "city": "Hyderabad",
        "state": "Telangana",
        "district": "Hyderabad",
    },
    "380001": {
        "pincode": "380001",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "district": "Ahmedabad",
    },
    "302001": {
        "pincode": "302001",
        "city": "Jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
    },
    "226001": {
        "pincode": "226001",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
    },
    "208001": {
        "pincode": "208001",
        "city": "Kanpur",
        "state": "Uttar Pradesh",
        "district": "Kanpur Nagar",
    },
    "462001": {
        "pincode": "462001",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
    },
    "751001": {
        "pincode": "751001",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "district": "Khordha",
    },
    "682001": {
        "pincode": "682001",
        "city": "Kochi",
        "state": "Kerala",
        "district": "Ernakulam",
    },
    "781001": {
        "pincode": "781001",
        "city": "Guwahati",
        "state": "Assam",
        "district": "Kamrup Metropolitan",
    },
    "160001": {
        "pincode": "160001",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "district": "Chandigarh",
    },
    "800001": {
        "pincode": "800001",
        "city": "Patna",
        "state": "Bihar",
        "district": "Patna",
    },
    "834001": {
        "pincode": "834001",
        "city": "Ranchi",
        "state": "Jharkhand",
        "district": "Ranchi",
    },
    "492001": {
        "pincode": "492001",
        "city": "Raipur",
        "state": "Chhattisgarh",
        "district": "Raipur",
    },
    "248001": {
        "pincode": "248001",
        "city": "Dehradun",
        "state": "Uttarakhand",
        "district": "Dehradun",
    },
    "403001": {
        "pincode": "403001",
        "city": "Panaji",
        "state": "Goa",
        "district": "North Goa",
    },
}